[2024-08-26 23:17:19,435: INFO: main: welcome to our custom log]
[2024-08-26 23:19:20,270: INFO: main: welcome to our custom log]
[2024-08-29 07:41:36,344: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 07:41:36,377: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 07:41:36,384: INFO: common: created directory at: artifacts]
[2024-08-29 07:41:36,390: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-29 07:43:03,495: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 07:43:03,498: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 07:43:03,500: INFO: common: created directory at: artifacts]
[2024-08-29 07:43:03,503: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-29 07:43:03,505: INFO: 3398215002: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 07:43:05,219: INFO: 3398215002: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 07:43:55,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 07:43:55,076: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 07:43:55,078: INFO: common: created directory at: artifacts]
[2024-08-29 07:43:55,081: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-29 07:43:55,083: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 07:44:40,226: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 08:27:27,379: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-29 08:27:27,384: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 08:27:27,386: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 08:27:27,387: INFO: common: created directory at: artifacts]
[2024-08-29 08:27:27,389: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-29 08:27:27,390: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 08:28:07,282: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 08:28:08,207: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:11:51,742: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:11:51,754: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:11:51,759: INFO: common: created directory at: artifacts]
[2024-08-30 20:11:51,762: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:11:53,146: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 20:20:35,368: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 20:20:35,372: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:20:35,376: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:20:35,378: INFO: common: created directory at: artifacts]
[2024-08-30 20:20:35,379: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 20:20:35,380: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:22:21,420: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:22:22,467: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:22:22,467: INFO: main: *******************]
[2024-08-30 20:22:22,467: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 20:22:22,470: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:22:22,473: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:22:22,475: INFO: common: created directory at: artifacts]
[2024-08-30 20:22:22,477: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:22:22,477: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 20:25:52,164: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 20:25:52,167: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:25:52,171: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:25:52,172: INFO: common: created directory at: artifacts]
[2024-08-30 20:25:52,173: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 20:25:52,173: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:26:19,181: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:26:20,327: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:26:20,328: INFO: main: *******************]
[2024-08-30 20:26:20,328: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 20:26:20,330: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:26:20,332: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:26:20,332: INFO: common: created directory at: artifacts]
[2024-08-30 20:26:20,333: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:26:20,333: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 20:28:40,085: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 20:28:40,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:28:40,092: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:28:40,093: INFO: common: created directory at: artifacts]
[2024-08-30 20:28:40,094: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 20:28:40,095: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:29:04,976: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:29:05,899: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:29:05,899: INFO: main: *******************]
[2024-08-30 20:29:05,899: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 20:29:05,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:29:05,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:29:05,904: INFO: common: created directory at: artifacts]
[2024-08-30 20:29:05,904: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:29:05,905: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 20:32:26,197: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 20:32:26,199: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:32:26,205: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:32:26,206: INFO: common: created directory at: artifacts]
[2024-08-30 20:32:26,207: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 20:32:26,207: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:32:50,820: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:32:51,939: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:32:51,941: INFO: main: *******************]
[2024-08-30 20:32:51,941: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 20:32:51,946: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:32:51,949: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:32:51,950: INFO: common: created directory at: artifacts]
[2024-08-30 20:32:51,950: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:32:51,951: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 21:05:48,479: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 21:05:48,482: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 21:05:48,487: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 21:05:48,488: INFO: common: created directory at: artifacts]
[2024-08-30 21:05:48,489: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 21:05:48,490: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 21:08:48,669: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 21:08:50,218: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 21:08:50,219: INFO: main: *******************]
[2024-08-30 21:08:50,219: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 21:08:50,254: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 21:08:50,271: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 21:08:50,277: INFO: common: created directory at: artifacts]
[2024-08-30 21:08:50,278: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 21:08:50,285: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 22:56:44,741: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 22:56:44,750: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 22:56:44,755: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 22:56:44,757: INFO: common: created directory at: artifacts]
[2024-08-30 22:56:44,758: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 22:56:44,758: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 22:57:55,530: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 22:57:56,447: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 22:57:56,447: INFO: main: *******************]
[2024-08-30 22:57:56,447: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 22:57:56,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 22:57:56,451: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 22:57:56,452: INFO: common: created directory at: artifacts]
[2024-08-30 22:57:56,452: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 22:57:56,453: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:02:58,807: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:02:58,810: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:02:58,813: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:02:58,815: INFO: common: created directory at: artifacts]
[2024-08-30 23:02:58,815: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:02:58,816: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:03:30,474: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:03:31,189: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:03:31,190: INFO: main: *******************]
[2024-08-30 23:03:31,190: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:03:31,192: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:03:31,193: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:03:31,194: INFO: common: created directory at: artifacts]
[2024-08-30 23:03:31,194: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:03:31,194: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:05:13,672: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:05:13,674: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:05:13,677: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:05:13,678: INFO: common: created directory at: artifacts]
[2024-08-30 23:05:13,678: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:05:13,678: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:05:52,742: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:05:53,432: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:05:53,432: INFO: main: *******************]
[2024-08-30 23:05:53,432: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:05:53,434: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:05:53,436: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:05:53,437: INFO: common: created directory at: artifacts]
[2024-08-30 23:05:53,437: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:05:53,438: ERROR: main: "'ConfigBox' object has no attribute 'image_size'"]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'IMAGE_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'IMAGE_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'IMAGE_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'IMAGE_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'image_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'image_size'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'image_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\config\configuration.py", line 46, in get_prepare_base_model_config
    params_image_size=self.params.IMAGE_SIZE,
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'image_size'"
[2024-08-30 23:07:08,867: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:07:08,870: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:07:08,873: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:07:08,874: INFO: common: created directory at: artifacts]
[2024-08-30 23:07:08,874: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:07:08,875: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:07:55,600: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:07:56,282: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:07:56,282: INFO: main: *******************]
[2024-08-30 23:07:56,282: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:07:56,284: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:07:56,286: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:07:56,287: INFO: common: created directory at: artifacts]
[2024-08-30 23:07:56,287: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:07:56,287: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:10:06,330: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:10:06,333: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:10:06,337: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:10:06,338: INFO: common: created directory at: artifacts]
[2024-08-30 23:10:06,339: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:10:06,339: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:10:39,388: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:10:40,131: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:10:40,131: INFO: main: *******************]
[2024-08-30 23:10:40,132: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:10:40,134: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:10:40,136: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:10:40,136: INFO: common: created directory at: artifacts]
[2024-08-30 23:10:40,137: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:10:40,137: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:17:40,226: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:17:40,229: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:17:40,233: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:17:40,235: INFO: common: created directory at: artifacts]
[2024-08-30 23:17:40,236: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:17:40,236: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:18:12,070: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:18:12,829: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:18:12,830: INFO: main: *******************]
[2024-08-30 23:18:12,830: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:18:12,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:18:12,834: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:18:12,834: INFO: common: created directory at: artifacts]
[2024-08-30 23:18:12,834: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:18:12,835: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:20:58,433: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:20:58,436: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:20:58,440: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:20:58,442: INFO: common: created directory at: artifacts]
[2024-08-30 23:20:58,442: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:20:58,442: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:21:20,949: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:21:21,727: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:21:21,727: INFO: main: *******************]
[2024-08-30 23:21:21,727: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:21:21,729: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:21:21,731: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:21:21,731: INFO: common: created directory at: artifacts]
[2024-08-30 23:21:21,732: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:21:22,420: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:21:23,635: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-08-30 23:43:40,617: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:43:40,620: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:43:40,624: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:43:40,626: INFO: common: created directory at: artifacts]
[2024-08-30 23:43:40,626: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:43:40,627: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:44:16,111: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:44:16,935: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:44:16,935: INFO: main: *******************]
[2024-08-30 23:44:16,935: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:44:16,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:44:16,939: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:44:16,939: INFO: common: created directory at: artifacts]
[2024-08-30 23:44:16,940: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:44:17,602: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:44:18,578: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
