[2024-08-26 23:17:19,435: INFO: main: welcome to our custom log]
[2024-08-26 23:19:20,270: INFO: main: welcome to our custom log]
[2024-08-29 07:41:36,344: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 07:41:36,377: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 07:41:36,384: INFO: common: created directory at: artifacts]
[2024-08-29 07:41:36,390: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-29 07:43:03,495: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 07:43:03,498: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 07:43:03,500: INFO: common: created directory at: artifacts]
[2024-08-29 07:43:03,503: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-29 07:43:03,505: INFO: 3398215002: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 07:43:05,219: INFO: 3398215002: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 07:43:55,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 07:43:55,076: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 07:43:55,078: INFO: common: created directory at: artifacts]
[2024-08-29 07:43:55,081: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-29 07:43:55,083: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 07:44:40,226: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 08:27:27,379: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-29 08:27:27,384: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 08:27:27,386: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 08:27:27,387: INFO: common: created directory at: artifacts]
[2024-08-29 08:27:27,389: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-29 08:27:27,390: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 08:28:07,282: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-29 08:28:08,207: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:11:51,742: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:11:51,754: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:11:51,759: INFO: common: created directory at: artifacts]
[2024-08-30 20:11:51,762: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:11:53,146: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 20:20:35,368: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 20:20:35,372: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:20:35,376: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:20:35,378: INFO: common: created directory at: artifacts]
[2024-08-30 20:20:35,379: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 20:20:35,380: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:22:21,420: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:22:22,467: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:22:22,467: INFO: main: *******************]
[2024-08-30 20:22:22,467: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 20:22:22,470: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:22:22,473: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:22:22,475: INFO: common: created directory at: artifacts]
[2024-08-30 20:22:22,477: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:22:22,477: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 20:25:52,164: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 20:25:52,167: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:25:52,171: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:25:52,172: INFO: common: created directory at: artifacts]
[2024-08-30 20:25:52,173: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 20:25:52,173: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:26:19,181: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:26:20,327: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:26:20,328: INFO: main: *******************]
[2024-08-30 20:26:20,328: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 20:26:20,330: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:26:20,332: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:26:20,332: INFO: common: created directory at: artifacts]
[2024-08-30 20:26:20,333: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:26:20,333: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 20:28:40,085: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 20:28:40,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:28:40,092: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:28:40,093: INFO: common: created directory at: artifacts]
[2024-08-30 20:28:40,094: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 20:28:40,095: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:29:04,976: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:29:05,899: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:29:05,899: INFO: main: *******************]
[2024-08-30 20:29:05,899: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 20:29:05,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:29:05,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:29:05,904: INFO: common: created directory at: artifacts]
[2024-08-30 20:29:05,904: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:29:05,905: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 20:32:26,197: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 20:32:26,199: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:32:26,205: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:32:26,206: INFO: common: created directory at: artifacts]
[2024-08-30 20:32:26,207: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 20:32:26,207: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:32:50,820: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:32:51,939: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 20:32:51,941: INFO: main: *******************]
[2024-08-30 20:32:51,941: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 20:32:51,946: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:32:51,949: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:32:51,950: INFO: common: created directory at: artifacts]
[2024-08-30 20:32:51,950: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:32:51,951: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 21:05:48,479: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 21:05:48,482: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 21:05:48,487: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 21:05:48,488: INFO: common: created directory at: artifacts]
[2024-08-30 21:05:48,489: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 21:05:48,490: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 21:08:48,669: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 21:08:50,218: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 21:08:50,219: INFO: main: *******************]
[2024-08-30 21:08:50,219: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 21:08:50,254: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 21:08:50,271: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 21:08:50,277: INFO: common: created directory at: artifacts]
[2024-08-30 21:08:50,278: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 21:08:50,285: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 22:56:44,741: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 22:56:44,750: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 22:56:44,755: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 22:56:44,757: INFO: common: created directory at: artifacts]
[2024-08-30 22:56:44,758: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 22:56:44,758: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 22:57:55,530: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 22:57:56,447: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 22:57:56,447: INFO: main: *******************]
[2024-08-30 22:57:56,447: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 22:57:56,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 22:57:56,451: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 22:57:56,452: INFO: common: created directory at: artifacts]
[2024-08-30 22:57:56,452: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 22:57:56,453: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:02:58,807: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:02:58,810: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:02:58,813: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:02:58,815: INFO: common: created directory at: artifacts]
[2024-08-30 23:02:58,815: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:02:58,816: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:03:30,474: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:03:31,189: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:03:31,190: INFO: main: *******************]
[2024-08-30 23:03:31,190: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:03:31,192: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:03:31,193: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:03:31,194: INFO: common: created directory at: artifacts]
[2024-08-30 23:03:31,194: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:03:31,194: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:05:13,672: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:05:13,674: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:05:13,677: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:05:13,678: INFO: common: created directory at: artifacts]
[2024-08-30 23:05:13,678: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:05:13,678: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:05:52,742: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:05:53,432: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:05:53,432: INFO: main: *******************]
[2024-08-30 23:05:53,432: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:05:53,434: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:05:53,436: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:05:53,437: INFO: common: created directory at: artifacts]
[2024-08-30 23:05:53,437: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:05:53,438: ERROR: main: "'ConfigBox' object has no attribute 'image_size'"]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'IMAGE_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'IMAGE_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'IMAGE_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'IMAGE_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'image_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'image_size'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'image_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\config\configuration.py", line 46, in get_prepare_base_model_config
    params_image_size=self.params.IMAGE_SIZE,
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'image_size'"
[2024-08-30 23:07:08,867: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:07:08,870: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:07:08,873: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:07:08,874: INFO: common: created directory at: artifacts]
[2024-08-30 23:07:08,874: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:07:08,875: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:07:55,600: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:07:56,282: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:07:56,282: INFO: main: *******************]
[2024-08-30 23:07:56,282: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:07:56,284: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:07:56,286: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:07:56,287: INFO: common: created directory at: artifacts]
[2024-08-30 23:07:56,287: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:07:56,287: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:10:06,330: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:10:06,333: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:10:06,337: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:10:06,338: INFO: common: created directory at: artifacts]
[2024-08-30 23:10:06,339: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:10:06,339: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:10:39,388: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:10:40,131: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:10:40,131: INFO: main: *******************]
[2024-08-30 23:10:40,132: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:10:40,134: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:10:40,136: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:10:40,136: INFO: common: created directory at: artifacts]
[2024-08-30 23:10:40,137: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:10:40,137: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:17:40,226: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:17:40,229: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:17:40,233: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:17:40,235: INFO: common: created directory at: artifacts]
[2024-08-30 23:17:40,236: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:17:40,236: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:18:12,070: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:18:12,829: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:18:12,830: INFO: main: *******************]
[2024-08-30 23:18:12,830: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:18:12,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:18:12,834: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:18:12,834: INFO: common: created directory at: artifacts]
[2024-08-30 23:18:12,834: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:18:12,835: ERROR: main: 'NoneType' object has no attribute 'params_image_size']
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    prepare_base_model.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.get_base_model()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\prepare_base_model.py", line 16, in get_base_model
    input_shape=self.config.params_image_size,
AttributeError: 'NoneType' object has no attribute 'params_image_size'
[2024-08-30 23:20:58,433: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:20:58,436: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:20:58,440: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:20:58,442: INFO: common: created directory at: artifacts]
[2024-08-30 23:20:58,442: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:20:58,442: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:21:20,949: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:21:21,727: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:21:21,727: INFO: main: *******************]
[2024-08-30 23:21:21,727: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:21:21,729: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:21:21,731: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:21:21,731: INFO: common: created directory at: artifacts]
[2024-08-30 23:21:21,732: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:21:22,420: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:21:23,635: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-08-30 23:43:40,617: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-30 23:43:40,620: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:43:40,624: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:43:40,626: INFO: common: created directory at: artifacts]
[2024-08-30 23:43:40,626: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 23:43:40,627: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:44:16,111: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 23:44:16,935: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-30 23:44:16,935: INFO: main: *******************]
[2024-08-30 23:44:16,935: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-30 23:44:16,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:44:16,939: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:44:16,939: INFO: common: created directory at: artifacts]
[2024-08-30 23:44:16,940: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 23:44:17,602: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:44:18,578: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-08-31 00:35:54,891: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-31 00:35:54,932: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-31 00:35:54,936: INFO: common: created directory at: artifacts]
[2024-08-31 00:35:54,941: INFO: common: created directory at: artifacts\training]
[2024-08-31 00:52:51,949: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-31 00:52:51,953: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-31 00:52:51,958: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-31 00:52:51,960: INFO: common: created directory at: artifacts]
[2024-08-31 00:52:51,961: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-31 00:52:51,962: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-31 00:53:08,822: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-31 00:53:09,738: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-31 00:53:09,738: INFO: main: *******************]
[2024-08-31 00:53:09,738: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-31 00:53:09,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-31 00:53:09,743: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-31 00:53:09,744: INFO: common: created directory at: artifacts]
[2024-08-31 00:53:09,745: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-31 00:53:10,458: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-31 00:53:10,826: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-08-31 00:53:10,826: INFO: main: *******************]
[2024-08-31 00:53:10,826: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-08-31 00:53:10,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-31 00:53:10,830: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-31 00:53:10,831: INFO: common: created directory at: artifacts]
[2024-08-31 00:53:10,832: INFO: common: created directory at: artifacts\training]
[2024-08-31 00:53:48,385: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-01 01:16:16,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 01:16:16,185: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 01:16:16,192: INFO: common: created directory at: artifacts]
[2024-09-01 01:16:31,665: INFO: common: json file saved at: scores.json]
[2024-09-01 01:16:37,350: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-01 01:16:38,108: INFO: builder_impl: Assets written to: C:\Users\NISHAN~1\AppData\Local\Temp\tmp9mfsej7x\model\data\model\assets]
[2024-09-01 01:25:30,257: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 01:25:30,278: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 01:25:30,282: INFO: common: created directory at: artifacts]
[2024-09-01 01:25:47,113: INFO: common: json file saved at: scores.json]
[2024-09-01 01:25:51,434: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-01 01:25:52,271: INFO: builder_impl: Assets written to: C:\Users\NISHAN~1\AppData\Local\Temp\tmp96yiofyj\model\data\model\assets]
[2024-09-01 01:27:00,371: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 01:27:00,379: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 01:27:00,380: INFO: common: created directory at: artifacts]
[2024-09-01 01:27:14,200: INFO: common: json file saved at: scores.json]
[2024-09-01 01:27:18,057: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-01 01:27:18,791: INFO: builder_impl: Assets written to: C:\Users\NISHAN~1\AppData\Local\Temp\tmpgpiz8tjm\model\data\model\assets]
[2024-09-01 01:32:57,442: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 01:32:57,450: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 01:32:57,452: INFO: common: created directory at: artifacts]
[2024-09-01 01:33:14,799: INFO: common: json file saved at: scores.json]
[2024-09-01 01:33:18,708: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-01 01:33:19,426: INFO: builder_impl: Assets written to: C:\Users\NISHAN~1\AppData\Local\Temp\tmphpjcbzp0\model\data\model\assets]
[2024-09-01 01:34:01,119: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 01:34:01,130: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 01:34:01,133: INFO: common: created directory at: artifacts]
[2024-09-01 01:34:16,323: INFO: common: json file saved at: scores.json]
[2024-09-01 01:34:20,220: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-01 01:34:20,960: INFO: builder_impl: Assets written to: C:\Users\NISHAN~1\AppData\Local\Temp\tmphdsf3160\model\data\model\assets]
[2024-09-01 12:11:11,264: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-01 12:11:11,268: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:11:11,272: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:11:11,273: INFO: common: created directory at: artifacts]
[2024-09-01 12:11:11,274: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-01 12:11:11,274: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:12:17,698: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:12:18,613: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-01 12:12:18,613: INFO: main: *******************]
[2024-09-01 12:12:18,613: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-01 12:12:18,617: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:12:18,619: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:12:18,620: INFO: common: created directory at: artifacts]
[2024-09-01 12:12:18,620: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-01 12:12:19,468: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-01 12:12:19,914: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-01 12:12:19,914: INFO: main: *******************]
[2024-09-01 12:12:19,914: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-01 12:12:19,916: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:12:19,918: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:12:19,919: INFO: common: created directory at: artifacts]
[2024-09-01 12:12:19,920: INFO: common: created directory at: artifacts\training]
[2024-09-01 12:12:58,075: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-01 12:12:58,075: INFO: main: *******************]
[2024-09-01 12:12:58,075: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-01 12:12:58,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:12:58,083: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:12:58,085: INFO: common: created directory at: artifacts]
[2024-09-01 12:13:09,960: INFO: common: json file saved at: scores.json]
[2024-09-01 12:13:09,961: INFO: common: json file saved at: scores.json]
[2024-09-01 12:13:11,659: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 401 != 200. Response body: '=============== ATTENTION! ===============

To use authentication, you must first: 
    Get your default access token from: https://dagshub.com/user/settings/tokens
    OR 
    Set a password: https://dagshub.com/user/settings/password 
==========================================']
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    model_evalution.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 401 != 200. Response body: '=============== ATTENTION! ===============

To use authentication, you must first: 
    Get your default access token from: https://dagshub.com/user/settings/tokens
    OR 
    Set a password: https://dagshub.com/user/settings/password 
=========================================='
[2024-09-01 12:15:16,964: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-01 12:15:16,968: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:15:16,969: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:15:16,970: INFO: common: created directory at: artifacts]
[2024-09-01 12:15:16,971: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-01 12:15:16,971: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:16:10,356: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:16:11,257: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-01 12:16:11,257: INFO: main: *******************]
[2024-09-01 12:16:11,257: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-01 12:16:11,260: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:16:11,262: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:16:11,263: INFO: common: created directory at: artifacts]
[2024-09-01 12:16:11,264: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-01 12:16:12,020: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-01 12:16:12,383: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-01 12:16:12,383: INFO: main: *******************]
[2024-09-01 12:16:12,383: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-01 12:16:12,386: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:16:12,388: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:16:12,389: INFO: common: created directory at: artifacts]
[2024-09-01 12:16:12,390: INFO: common: created directory at: artifacts\training]
[2024-09-01 12:16:50,702: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-01 12:16:50,703: INFO: main: *******************]
[2024-09-01 12:16:50,703: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-01 12:16:50,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:16:50,713: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:16:50,715: INFO: common: created directory at: artifacts]
[2024-09-01 12:17:02,578: INFO: common: json file saved at: scores.json]
[2024-09-01 12:17:02,579: INFO: common: json file saved at: scores.json]
[2024-09-01 12:17:03,679: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 401 != 200. Response body: '=============== ATTENTION! ===============

To use authentication, you must first: 
    Get your default access token from: https://dagshub.com/user/settings/tokens
    OR 
    Set a password: https://dagshub.com/user/settings/password 
==========================================']
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    model_evalution.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 401 != 200. Response body: '=============== ATTENTION! ===============

To use authentication, you must first: 
    Get your default access token from: https://dagshub.com/user/settings/tokens
    OR 
    Set a password: https://dagshub.com/user/settings/password 
=========================================='
[2024-09-01 12:23:09,146: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-01 12:23:09,157: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:23:09,167: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:23:09,168: INFO: common: created directory at: artifacts]
[2024-09-01 12:23:09,168: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-01 12:23:09,168: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:25:31,686: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:25:32,719: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-01 12:25:32,719: INFO: main: *******************]
[2024-09-01 12:25:32,719: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-01 12:25:32,723: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:25:32,726: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:25:32,727: INFO: common: created directory at: artifacts]
[2024-09-01 12:25:32,728: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-01 12:25:33,508: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-01 12:25:33,951: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-01 12:25:33,951: INFO: main: *******************]
[2024-09-01 12:25:33,951: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-01 12:25:33,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:25:33,956: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:25:33,957: INFO: common: created directory at: artifacts]
[2024-09-01 12:25:33,957: INFO: common: created directory at: artifacts\training]
[2024-09-01 12:26:17,788: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-01 12:26:17,788: INFO: main: *******************]
[2024-09-01 12:26:17,788: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-01 12:26:17,793: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:26:17,797: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:26:17,800: INFO: common: created directory at: artifacts]
[2024-09-01 12:26:30,807: INFO: common: json file saved at: scores.json]
[2024-09-01 12:26:30,810: INFO: common: json file saved at: scores.json]
[2024-09-01 12:26:32,436: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 401 != 200. Response body: '=============== ATTENTION! ===============

To use authentication, you must first: 
    Get your default access token from: https://dagshub.com/user/settings/tokens
    OR 
    Set a password: https://dagshub.com/user/settings/password 
==========================================']
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    model_evalution.main()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 401 != 200. Response body: '=============== ATTENTION! ===============

To use authentication, you must first: 
    Get your default access token from: https://dagshub.com/user/settings/tokens
    OR 
    Set a password: https://dagshub.com/user/settings/password 
=========================================='
[2024-09-01 12:27:40,422: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-01 12:27:40,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:27:40,427: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:27:40,427: INFO: common: created directory at: artifacts]
[2024-09-01 12:27:40,428: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-01 12:27:40,429: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:28:55,425: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:28:56,274: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-01 12:28:56,274: INFO: main: *******************]
[2024-09-01 12:28:56,274: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-01 12:28:56,276: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:28:56,278: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:28:56,279: INFO: common: created directory at: artifacts]
[2024-09-01 12:28:56,279: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-01 12:28:56,875: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-01 12:28:57,162: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-01 12:28:57,163: INFO: main: *******************]
[2024-09-01 12:28:57,163: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-01 12:28:57,165: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:28:57,167: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:28:57,167: INFO: common: created directory at: artifacts]
[2024-09-01 12:28:57,168: INFO: common: created directory at: artifacts\training]
[2024-09-01 12:29:39,110: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-01 12:29:39,111: INFO: main: *******************]
[2024-09-01 12:29:39,111: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-01 12:29:39,114: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:29:39,119: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:29:39,121: INFO: common: created directory at: artifacts]
[2024-09-01 12:29:50,667: INFO: common: json file saved at: scores.json]
[2024-09-01 12:29:50,668: INFO: common: json file saved at: scores.json]
[2024-09-01 12:29:54,963: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-01 12:29:55,655: INFO: builder_impl: Assets written to: C:\Users\NISHAN~1\AppData\Local\Temp\tmp3du1qwc9\model\data\model\assets]
[2024-09-01 12:32:16,478: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-01 12:38:19,300: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-01 12:38:19,304: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:38:19,307: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:38:19,307: INFO: common: created directory at: artifacts]
[2024-09-01 12:38:19,308: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-01 12:38:19,308: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:38:51,220: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:38:52,089: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-01 12:38:52,089: INFO: main: *******************]
[2024-09-01 12:38:52,089: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-01 12:38:52,093: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:38:52,094: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:38:52,095: INFO: common: created directory at: artifacts]
[2024-09-01 12:38:52,095: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-01 12:38:52,717: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-01 12:38:53,034: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-01 12:38:53,034: INFO: main: *******************]
[2024-09-01 12:38:53,034: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-01 12:38:53,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:38:53,040: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:38:53,041: INFO: common: created directory at: artifacts]
[2024-09-01 12:38:53,042: INFO: common: created directory at: artifacts\training]
[2024-09-01 12:41:15,793: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-01 12:41:15,793: INFO: main: *******************]
[2024-09-01 12:41:15,793: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-01 12:41:15,797: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:41:15,799: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:41:15,800: INFO: common: created directory at: artifacts]
[2024-09-01 12:41:38,350: INFO: common: json file saved at: scores.json]
[2024-09-01 12:41:38,352: INFO: common: json file saved at: scores.json]
[2024-09-01 12:41:42,317: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-01 12:41:43,129: INFO: builder_impl: Assets written to: C:\Users\NISHAN~1\AppData\Local\Temp\tmpfug85q7n\model\data\model\assets]
[2024-09-01 12:44:40,796: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-01 12:44:59,529: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-01 12:44:59,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:44:59,537: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:44:59,537: INFO: common: created directory at: artifacts]
[2024-09-01 12:44:59,538: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-01 12:44:59,538: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:45:24,685: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 12:45:25,509: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-01 12:45:25,509: INFO: main: *******************]
[2024-09-01 12:45:25,509: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-01 12:45:25,513: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:45:25,516: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:45:25,516: INFO: common: created directory at: artifacts]
[2024-09-01 12:45:25,517: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-01 12:45:26,133: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-01 12:45:26,430: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-01 12:45:26,431: INFO: main: *******************]
[2024-09-01 12:45:26,431: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-01 12:45:26,434: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:45:26,436: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:45:26,436: INFO: common: created directory at: artifacts]
[2024-09-01 12:45:26,437: INFO: common: created directory at: artifacts\training]
[2024-09-01 12:50:07,281: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-01 12:50:07,282: INFO: main: *******************]
[2024-09-01 12:50:07,282: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-01 12:50:07,287: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 12:50:07,290: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 12:50:07,291: INFO: common: created directory at: artifacts]
[2024-09-01 12:50:29,675: INFO: common: json file saved at: scores.json]
[2024-09-01 12:50:29,677: INFO: common: json file saved at: scores.json]
[2024-09-01 12:50:33,605: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-01 12:50:34,304: INFO: builder_impl: Assets written to: C:\Users\NISHAN~1\AppData\Local\Temp\tmp277_0fpe\model\data\model\assets]
[2024-09-01 12:53:16,112: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-01 14:33:29,428: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-01 14:33:29,432: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 14:33:29,437: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 14:33:29,437: INFO: common: created directory at: artifacts]
[2024-09-01 14:33:29,438: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-01 14:33:29,439: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 14:34:25,911: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 14:34:27,070: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-01 14:34:27,070: INFO: main: *******************]
[2024-09-01 14:34:27,070: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-01 14:34:27,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 14:34:27,076: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 14:34:27,077: INFO: common: created directory at: artifacts]
[2024-09-01 14:34:27,078: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-01 14:34:27,880: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-01 14:34:28,276: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-01 14:34:28,277: INFO: main: *******************]
[2024-09-01 14:34:28,277: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-01 14:34:28,279: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 14:34:28,281: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 14:34:28,283: INFO: common: created directory at: artifacts]
[2024-09-01 14:34:28,284: INFO: common: created directory at: artifacts\training]
[2024-09-01 14:36:51,043: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-01 14:36:51,044: INFO: main: *******************]
[2024-09-01 14:36:51,044: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-01 14:36:51,049: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 14:36:51,056: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 14:36:51,058: INFO: common: created directory at: artifacts]
[2024-09-01 14:37:02,763: INFO: common: json file saved at: scores.json]
[2024-09-01 14:37:02,764: INFO: common: json file saved at: scores.json]
[2024-09-01 14:37:07,257: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-01 14:37:07,928: INFO: builder_impl: Assets written to: C:\Users\NISHAN~1\AppData\Local\Temp\tmp2asgmct9\model\data\model\assets]
[2024-09-01 14:41:40,242: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-01 15:23:54,353: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-01 15:23:54,357: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 15:23:54,360: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 15:23:54,361: INFO: common: created directory at: artifacts]
[2024-09-01 15:23:54,361: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-01 15:23:54,362: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 15:24:55,905: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1ARkV6dRr9Nx9GiEkbrjSzphvEo1nyRYm/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-01 15:24:56,886: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-01 15:25:13,235: INFO: stage_02_prepare_base_model: *******************]
[2024-09-01 15:25:13,236: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-01 15:25:13,239: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 15:25:13,241: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 15:25:13,241: INFO: common: created directory at: artifacts]
[2024-09-01 15:25:13,242: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-01 15:25:13,937: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-01 15:25:15,044: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-01 15:25:24,107: INFO: stage_03_model_training: *******************]
[2024-09-01 15:25:24,107: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-09-01 15:25:24,110: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 15:25:24,112: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 15:25:24,112: INFO: common: created directory at: artifacts]
[2024-09-01 15:25:24,113: INFO: common: created directory at: artifacts\training]
[2024-09-01 15:27:45,409: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-01 15:27:56,762: INFO: stage_04_model_evaluation: *******************]
[2024-09-01 15:27:56,762: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-01 15:27:56,765: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-01 15:27:56,768: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-01 15:27:56,769: INFO: common: created directory at: artifacts]
[2024-09-01 15:28:09,178: INFO: common: json file saved at: scores.json]
[2024-09-01 15:28:09,179: INFO: common: json file saved at: scores.json]
[2024-09-01 15:28:09,180: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-01 22:32:47,057: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.170:8080]
[2024-09-01 22:32:47,058: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-01 22:33:31,452: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.170:8080]
[2024-09-01 22:33:31,453: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-01 22:33:36,968: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:33:36] "GET / HTTP/1.1" 200 -]
[2024-09-01 22:34:41,829: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-09-01 22:34:41,840: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:34:41] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-01 22:35:30,890: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:35:30] "GET / HTTP/1.1" 200 -]
[2024-09-01 22:35:44,996: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-09-01 22:35:44,998: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:35:44] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-01 22:37:07,346: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:37:07] "GET / HTTP/1.1" 200 -]
[2024-09-01 22:37:48,171: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-09-01 22:37:48,173: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:37:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-01 22:42:16,512: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.170:8080]
[2024-09-01 22:42:16,513: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-01 22:42:58,014: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:42:58] "GET / HTTP/1.1" 200 -]
[2024-09-01 22:43:05,407: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\nishant thakur\kidney_disease_classification_deep_learning_project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model("artifacts\training\model.h5")
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\nishant thakur\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts	raining\model.h5
[2024-09-01 22:43:05,420: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:43:05] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-01 22:44:41,019: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.170:8080]
[2024-09-01 22:44:41,020: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-01 22:44:58,349: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:44:58] "GET / HTTP/1.1" 200 -]
[2024-09-01 22:45:06,845: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:45:06] "POST /predict HTTP/1.1" 200 -]
[2024-09-01 22:45:32,614: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:45:32] "POST /predict HTTP/1.1" 200 -]
[2024-09-01 22:45:43,378: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:45:43] "GET / HTTP/1.1" 200 -]
[2024-09-01 22:45:52,434: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:45:52] "POST /predict HTTP/1.1" 200 -]
[2024-09-01 22:46:01,593: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:46:01] "POST /predict HTTP/1.1" 200 -]
[2024-09-01 22:46:46,947: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001FA988C7940> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-09-01 22:46:46,956: INFO: _internal: 127.0.0.1 - - [01/Sep/2024 22:46:46] "POST /predict HTTP/1.1" 200 -]
